### PR TITLE
refactor the installer for helm3 support

### PR DESCRIPTION
**Pull request by jurgenweber**

### CODE REVIEW

**Comment by sco11morgan** [comment]
Helm 3 support would be great

**Comment by jurgenweber** [comment]
yeah, I had more changes in master. I am using this in my CI so it works. Can you test it against helm2 and ensure it still works and then it can be merged.

**Comment by sstarcher** [comment]
I'll try and test it out tomorrow against my helm 2 setup.

**Comment by sstarcher** [comment]
I made the following changes to get it to work with v2
```
diff --git a/install-binary.sh b/install-binary.sh
index 28b970a..7043cb3 100755
--- a/install-binary.sh
+++ b/install-binary.sh
@@ -5,7 +5,12 @@
 PROJECT_NAME="helm-release"
 PROJECT_GH="sstarcher/$PROJECT_NAME"

-helm_version=$(helm version --template '{{ .Version }}')
+helm_version=$(helm version --client --template '{{ .Version }}')
+if [ "${helm_version}" == "<no value>" ]; then
+  # Assume this means v2
+  helm_version="v2"
+fi
+
 if [ "${helm_version:0:2}" == "v2" ]; then
   : "${HELM_PLUGIN_PATH:="$(helm home)/plugins/helm-release"}"
```

**Comment by jurgenweber** [comment]
ok, added and pushed.

**Comment by sstarcher** [comment]
Thanks for the contribution

**Pull request merged**
