### PR TITLE
add support for charts as the source of version information

### PR DESCRIPTION
**Pull request by sstarcher**

### CODE REVIEW

**Comment by jurgenweber** [comment]
so, the plugin is updated:
```
$ helm release
Error: requires at least 1 arg(s), only received 0
Usage:
  helm-release [CHART_PATH] [flags]

Flags:
      --bump string              Specifies to bump major, minor, or patch when using print-computed-version
      --config string            config file (default is $HOME/.helm-release.yaml)
  -h, --help                     help for helm-release
      --path string              Sets the path to the image tag to modify in values.yaml (default "image.tag")
      --print-computed-version   Print the computed version string to stdout
      --source string            Specifies the source of the version information options (git, helm) (default "git")
  -t, --tag string               Sets the docker image tag in values.yaml
```
I then have a chart:
```
$ cat helm-chart/Chart.yaml
apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: helm-chart
version: 2.53.1
```
and we try some commands:
```
$ helm release helm-chart --source helm --print-computed-version --bump minor
2.54.0
$ helm release helm-chart --source helm --print-computed-version --bump major
3.0.0 
$ helm release helm-chart --source helm --print-computed-version --bump patch
2.53.
```
and these commands fail:
```
helm release helm-chart --source helm
Error: major, minor, and patch are the only valid options for Next
Usage:
  helm-release [CHART_PATH] [flags]

Flags:
      --bump string              Specifies to bump major, minor, or patch when using print-computed-version
      --config string            config file (default is $HOME/.helm-release.yaml)
  -h, --help                     help for helm-release
      --path string              Sets the path to the image tag to modify in values.yaml (default "image.tag")
      --print-computed-version   Print the computed version string to stdout
      --source string            Specifies the source of the version information options (git, helm) (default "git")
  -t, --tag string               Sets the docker image tag in values.yaml

INFO[0000] major, minor, and patch are the only valid options for Next
Error: plugin "release" exited with error
```
but this last command I would expect to work and update the Chart.yaml just like:
```
$ helm release helm-chart --source git
INFO[0000] updating the Chart.yaml to version 2.53.1-7+f82e727
```

Thanks!

**Comment by sstarcher** [comment]
The intent of the helm source was to require `--bump`, but I should make the error message better.
`helm release helm-chart --source helm --bump patch` should work

Let me know if that's not how you think it should work.

**Comment by jurgenweber** [comment]
oh, yes. I see. That is perfect. Lets fix up the error message and maybe make it clearer in the project readme and all good! Thank you!

**Comment by sstarcher** [comment]
updated check it out again.

**Pull request merged**
